/* ==========================================================================
   Jory — AI-assisted systems engineering
   Client-side i18n (en / zh-TW / zh-CN / fr) + navigation. No dependencies.
   ========================================================================== */

(function () {
  "use strict";

  var SUPPORTED = ["en", "zh-TW", "zh-CN", "fr"];
  var DEFAULT_LANG = "en";
  var STORAGE_KEY = "lang";

  var OG_LOCALE = {
    "en": "en_US",
    "zh-TW": "zh_TW",
    "zh-CN": "zh_CN",
    "fr": "fr_FR"
  };

  /* ── dictionaries ──────────────────────────────────────────────────── */

  var I18N = {};

  I18N["en"] = {
    "meta.title": "Jory — AI-Assisted Systems Engineering Workflow",
    "meta.desc": "Evidence-grounded AI-assisted software engineering, persistent semantic memory, executable verification, Rust systems, and trading infrastructure.",

    "a11y.skip": "Skip to content",
    "a11y.menu": "Open menu",
    "a11y.nav": "Main",
    "a11y.lang": "Language",

    "nav.brandsub": "AI-assisted systems engineering",
    "nav.how": "Approach",
    "nav.workflow": "Workflow",
    "nav.reliability": "Reliability",
    "nav.memory": "Memory",
    "nav.projects": "Projects",

    "hero.eyebrow": "Rust systems & trading infrastructure",
    "hero.title": "Architect-led, AI-assisted engineering",
    "hero.sub": "Evidence-grounded agents, persistent semantic memory, executable verification, and production-oriented engineering.",
    "hero.cta1": "View the workflow",
    "hero.cta2": "View GitHub",
    "hero.record.title": "verification record",
    "hero.record.note": "schema",
    "hero.record.k1": "claim",
    "hero.record.v1": "agent states the fan-out never blocks ingest",
    "hero.record.k2": "source of truth",
    "hero.record.v2": "repository code + integration test",
    "hero.record.k3": "verification",
    "hero.record.v3": "cargo test — executed, observed",
    "hero.record.k4": "state",
    "hero.record.foot": "Without the third line, the first line is only a claim.",

    "how.kicker": "position",
    "how.title": "How I use AI",
    "how.lead": "I don't treat AI as a code-generation shortcut. I run agents inside a structured engineering workflow and work primarily as the architect and system designer. Agent output is a proposal: it has to be grounded, constrained and verified before it becomes part of a system.",
    "how.ai.title": "The agent does",
    "how.ai.1": "Project evaluation",
    "how.ai.2": "Requirement analysis",
    "how.ai.3": "Architecture planning",
    "how.ai.4": "Code generation",
    "how.ai.5": "Refactoring",
    "how.ai.6": "Implementation",
    "how.ai.7": "White-box testing",
    "how.ai.8": "Black-box testing",
    "how.ai.9": "Integration testing",
    "how.ai.10": "Executable validation",
    "how.ai.11": "Documentation",
    "how.ai.12": "Long-term project memory",
    "how.human.title": "I stay responsible for",
    "how.human.1": "Architecture",
    "how.human.2": "Constraints",
    "how.human.3": "Trade-offs",
    "how.human.4": "Acceptance criteria",
    "how.human.5": "Risk",
    "how.human.6": "Verification",
    "how.human.7": "Final decisions",
    "how.note": "AI is not an authority in this workflow. It is an engineering worker whose output is reviewed like any other contribution.",

    "wf.kicker": "process",
    "wf.title": "End-to-end engineering workflow",
    "wf.lead": "The same sequence runs from a first feasibility read through to what gets written back into long-term memory. Each stage has an output someone else could check.",
    "wf.s1.t": "Project evaluation",
    "wf.s1.d": "Scope, feasibility, and whether the problem is worth solving in the shape it arrived in.",
    "wf.s2.t": "Evidence collection",
    "wf.s2.d": "Inspect the repository, documentation, schemas, interfaces and runtime state before deciding anything.",
    "wf.s3.t": "Architecture and constraints",
    "wf.s3.d": "Boundaries, invariants, latency budget and failure behaviour — defined by me, stated explicitly to the agent.",
    "wf.s4.t": "Implementation planning",
    "wf.s4.d": "Decomposition into tasks small enough to review and verify one at a time.",
    "wf.s5.t": "AI-assisted development",
    "wf.s5.d": "Code generation, refactoring and test drafting, bounded by the constraints set in stage three.",
    "wf.s6.t": "Executable verification",
    "wf.s6.d": "Compiler, test suites, integration and black-box runs, benchmarks, runtime observation, diff review.",
    "wf.s7.t": "Post-implementation review",
    "wf.s7.d": "Compare the result against the acceptance criteria — not against the agent's own summary of its work.",
    "wf.s8.t": "Persistent knowledge update",
    "wf.s8.d": "Verified conclusions, and only verified conclusions, are written back into long-term project memory.",
    "wf.sys1.t": "System one — reliability",
    "wf.sys1.d": "Hallucination control. Keeps the agent grounded in the actual system rather than in model priors.",
    "wf.sys1.link": "Three-layer model",
    "wf.sys2.t": "System two — context",
    "wf.sys2.d": "Persistent memory. Keeps knowledge from being lost between sessions and rediscovered at cost.",
    "wf.sys2.link": "Semantic memory",

    "rel.kicker": "reliability",
    "rel.title": "Three-layer hallucination control",
    "rel.lead": "This does not eliminate hallucination. It is designed to reduce the risk and to make unsupported claims easy to detect — early, and by something other than the model.",
    "rel.l1.t": "Evidence-driven instruction",
    "rel.l1.rule": "Inspect before acting. Evidence before assumptions.",
    "rel.l1.d": "Before implementation, the agent is instructed to inspect the real environment — code, documentation, interfaces, schemas, runtime state, data — and to bring back what it found. The instruction framework matters; the product name behind it does not. Model knowledge is never allowed to stand in as project truth.",
    "rel.l2.t": "Explicit source of truth",
    "rel.l2.rule": "Unknown is a valid state.",
    "rel.l2.d": "Execution defines which sources are authoritative: repository code, architecture documents, API schemas, specifications, tests, runtime behaviour, real datasets, verified engineering decisions. Every statement carries a state, so a missing fact never quietly becomes an invented assumption.",
    "rel.l3.t": "Executable verification",
    "rel.l3.rule": "A claim is not proof. An execution result is evidence.",
    "rel.l3.d": "An agent saying that something works proves nothing. Authority belongs to executable systems and observable results, not to the model's explanation of its own output.",
    "rel.l3.m1": "integration tests",
    "rel.l3.m2": "white-box tests",
    "rel.l3.m3": "black-box tests",
    "rel.l3.m4": "benchmarks",
    "rel.l3.m5": "runtime observation",
    "rel.l3.m6": "real queries, real output",
    "rel.fig.cap": "Diagram A — how a claim becomes a verified result",
    "rel.fig.n1": "Instruction",
    "rel.fig.n2": "Evidence collection",
    "rel.fig.n3": "Source of truth",
    "rel.fig.n4": "Implementation",
    "rel.fig.n5": "Executable verification",

    "mem.kicker": "context",
    "mem.title": "Persistent semantic memory",
    "mem.lead": "Long projects run across many sessions and many agent contexts. I keep engineering knowledge in a document-backed external memory and retrieve it semantically, instead of reloading an entire knowledge base into every session.",
    "mem.fig.cap": "Diagram B — retrieval and write-back loop",
    "mem.fig.n1": "Notion / Markdown knowledge base",
    "mem.fig.n2": "Structured project documents",
    "mem.fig.n3": "Chunking and embeddings",
    "mem.fig.n4": "Vector similarity retrieval",
    "mem.fig.n5": "Relevant context selection",
    "mem.fig.n6": "Agent context injection",
    "mem.fig.n7": "Development session",
    "mem.fig.n8": "Verified findings",
    "mem.fig.n9": "Knowledge base update",
    "mem.holds.t": "What the memory holds",
    "mem.holds.1": "Notion workspace and structured Markdown",
    "mem.holds.2": "Project and architecture documentation",
    "mem.holds.3": "Decision records",
    "mem.holds.4": "Research and implementation notes",
    "mem.holds.5": "Verified findings",
    "mem.honest.t": "What vector search does, and doesn't",
    "mem.honest.d": "Vector similarity does not guarantee correctness. It improves retrieval relevance and context precision: the agent sees the most semantically relevant documents instead of an indiscriminate dump of the whole knowledge base.",
    "mem.reduce.t": "It reduces:",
    "mem.reduce.1": "Irrelevant context",
    "mem.reduce.2": "Context dilution",
    "mem.reduce.3": "Cross-session knowledge loss",
    "mem.reduce.4": "Repeated rediscovery of the same facts",
    "mem.gate.t": "The write-back gate",
    "mem.gate.d": "Only verified conclusions are promoted into persistent memory. This is what keeps a hallucination from being stored once and then retrieved as established fact by every session after it.",
    "mem.gate.n1": "Agent output",
    "mem.gate.n2": "Verification",
    "mem.gate.n3": "Verified knowledge",
    "mem.gate.n4": "Persistent memory",
    "mem.term.1": "Document-backed external memory",
    "mem.term.2": "Semantic retrieval",
    "mem.term.3": "Persistent engineering memory",
    "mem.term.4": "RAG-style context retrieval",
    "mem.term.5": "Vector similarity search",
    "mem.term.6": "Context injection",

    "arch.kicker": "role",
    "arch.title": "Architect-led development",
    "arch.lead": "I increasingly work at the architecture and orchestration layer rather than typing every implementation detail by hand. This is AI-augmented engineering — the judgement, the constraints and the accountability stay with me.",
    "arch.n1": "Define system boundaries",
    "arch.n2": "Define constraints",
    "arch.n3": "Break down tasks",
    "arch.n4": "Delegate to agents",
    "arch.n5": "Review implementation",
    "arch.n6": "Verify results",
    "arch.n7": "Integrate knowledge",
    "arch.used.t": "Used on real engineering work",
    "arch.used.1": "Project feasibility evaluation",
    "arch.used.2": "Legacy system analysis",
    "arch.used.3": "Software architecture",
    "arch.used.4": "System decomposition",
    "arch.used.5": "Implementation planning",
    "arch.used.6": "Rust code generation",
    "arch.used.7": "Refactoring",
    "arch.used.8": "White-box testing",
    "arch.used.9": "Black-box testing",
    "arch.used.10": "Integration testing",
    "arch.used.11": "Debugging",
    "arch.used.12": "Performance evaluation",
    "arch.used.13": "Post-implementation review",
    "arch.used.14": "Technical documentation",
    "arch.tag.1": "AI-augmented engineering",
    "arch.tag.2": "Architect-led agent development",
    "arch.tag.3": "Evidence-grounded agent workflow",

    "proj.kicker": "evidence",
    "proj.title": "AI-assisted engineering case studies",
    "proj.lead": "Two Rust projects built with this workflow. Both repositories are public; the reasoning is in the READMEs.",
    "proj.repo": "Repository",
    "proj.bg": "Background",
    "proj.decisions": "Key decisions",
    "proj.tradeoff": "Trade-off philosophy",
    "proj.problem": "Engineering problem",
    "proj.outcome": "Outcome",
    "proj.myrole": "My role",
    "proj.airole": "The agent's role",
    "proj.stack": "Stack",
    "proj.read": "Read more",

    "p1.tagline": "Rust market-data middleware. Take-home engineering assignment from a leading trading firm.",
    "p1.bg": "The upstream emits a continuous stream of <code>BookMessage</code> order-book updates across many instruments. The service has to maintain the latest snapshot per instrument, serve request/response snapshot access, publish real-time updates to many subscribers, isolate slow consumers, and keep slow or disconnected clients away from the ingest hot path — for local and remote clients alike. Transport, fan-out behaviour, snapshot representation and wire subscription semantics were deliberately left open as engineering design decisions.",
    "p1.d1.t": "Non-blocking ingest",
    "p1.d1.d": "The hot path never waits on subscribers. Fan-out is non-blocking, so a slow consumer cannot back-pressure ingest.",
    "p1.d2.t": "Subscriber isolation",
    "p1.d2.d": "Each subscriber gets an independent bounded queue. When a queue fills, messages are dropped for that subscriber alone, and a cumulative dropped-message count makes the loss observable rather than silent.",
    "p1.d3.t": "Clear abstraction boundary",
    "p1.d3.d": "The upstream simulator sits behind an <code>Upstream</code> trait, so the real production feed can replace it without changing the rest of the service.",
    "p1.d4.t": "Transport",
    "p1.d4.d": "gRPC over HTTP/2 for cross-host clients: request/response for snapshots, server streaming for subscriptions.",
    "p1.trade": "The design deliberately favours predictability, failure isolation, correctness and operational safety, while keeping the hot path low-latency and non-blocking.",
    "p1.feedback": "In the interview discussion, the interviewer described the design as \"the safest\" among the submissions. I read that as the result of a deliberate trade-off rather than a verdict on which submission was best: a conservative architecture balancing low latency against subscriber isolation, explicit failure behaviour and operational safety.",
    "p1.fig.cap": "Ingest and fan-out path",
    "p1.fig.alt": "FeedSubscriber feeds the ingest loop, which writes latest snapshots into a DashMap and publishes to a pub/sub bus with one bounded queue per subscriber, exposed over tonic gRPC.",
    "p1.fig.snap": "latest snapshots",
    "p1.fig.bus": "pub/sub bus",
    "p1.fig.queue": "per-subscriber bounded queue",
    "p1.role": "System design, constraints, latency and failure requirements, and every trade-off decision.",
    "p1.ai": "Interpreting the assignment, exploring architectures, laying out trade-offs, implementation planning, Rust code generation, test planning, review support, verification runs.",
    "p1.stack.1": "bounded queues",
    "p1.stack.2": "deterministic integration tests",
    "p1.link.assignment": "Original assignment",
    "p1.link.impl": "Implementation and design notes",

    "p2.tagline": "A Rust-side Stark signing compatibility layer, built for an EdgeX exchange integration.",
    "p2.bg": "While building an EdgeX exchange integration at Binquant, the exchange required Stark-based cryptographic signing. The Rust StarkNet-related libraries available at the time did not produce signatures compatible with the exchange's required authentication flow. With AI assistance I investigated the signing algorithm and implemented the Rust-side cryptographic logic the integration needed.",
    "p2.prob": "Reproducing the signing pipeline end to end: StarkCurve elliptic-curve operations, Pedersen hashing, order hash construction, deterministic signing, L2 order fields, fee calculation and key derivation — each step matching the exchange byte for byte, because a signature is either accepted or it is not.",
    "p2.outcome": "A working Rust implementation that produces signatures the exchange accepts, integrated into the trading system's exchange connectivity workflow.",
    "p2.note": "This is an implementation and compatibility solution. StarkCurve, Pedersen hashing and the StarkNet signing scheme are existing designs; the work here is reproducing them correctly in Rust.",
    "p2.impl.t": "Implemented components",
    "p2.impl.1": "Pedersen hash",
    "p2.impl.2": "limit-order hash",
    "p2.impl.3": "StarkNet-style signing",
    "p2.impl.4": "L2 order-field construction",
    "p2.impl.5": "private-key derivation",
    "p2.ai": "Investigating specifications, comparing implementations, translating algorithm concepts into Rust, debugging incompatibilities, generating implementation scaffolding, validating intermediate calculations against known values.",
    "p2.role": "Defining the correctness requirements, verifying compatibility against the exchange, reviewing the cryptographic behaviour, and integrating the result into the trading system.",

    "princ.kicker": "principles",
    "princ.title": "Engineering principles",
    "princ.1": "Evidence before assumptions.",
    "princ.2": "Unknown is better than invented.",
    "princ.3": "AI output is a proposal, not an authority.",
    "princ.4": "Executable results outrank explanations.",
    "princ.5": "Only verified knowledge becomes persistent memory.",
    "princ.6": "Architecture and constraints stay human responsibilities.",
    "princ.7": "Optimise context quality, not context quantity.",

    "foot.role": "Rust systems and trading infrastructure engineering",
    "foot.note": "Static page. No frameworks, no build step."
  };

  I18N["zh-TW"] = {
    "meta.title": "Jory — AI 輔助系統工程工作流程",
    "meta.desc": "以證據為基礎的 AI 輔助軟體工程、持久化語意記憶、可執行驗證、Rust 系統與交易基礎設施。",

    "a11y.skip": "跳至主要內容",
    "a11y.menu": "開啟選單",
    "a11y.nav": "主選單",
    "a11y.lang": "語言",

    "nav.brandsub": "AI 輔助系統工程",
    "nav.how": "方法",
    "nav.workflow": "工作流程",
    "nav.reliability": "可靠性",
    "nav.memory": "記憶",
    "nav.projects": "專案",

    "hero.eyebrow": "Rust 系統與交易基礎設施",
    "hero.title": "以架構師為主導的 AI 輔助工程",
    "hero.sub": "以證據為基礎的 AI agent、持久化語意記憶、可執行驗證，以及面向生產環境的工程實踐。",
    "hero.cta1": "查看工作流程",
    "hero.cta2": "前往 GitHub",
    "hero.record.title": "驗證紀錄",
    "hero.record.note": "格式範例",
    "hero.record.k1": "主張",
    "hero.record.v1": "agent 宣稱 fan-out 不會阻塞 ingest",
    "hero.record.k2": "事實來源",
    "hero.record.v2": "專案程式碼 + 整合測試",
    "hero.record.k3": "驗證方式",
    "hero.record.v3": "cargo test — 實際執行並觀察結果",
    "hero.record.k4": "狀態",
    "hero.record.foot": "少了第三行，第一行就只是一個未經證實的說法。",

    "how.kicker": "定位",
    "how.title": "我如何使用 AI",
    "how.lead": "我不把 AI 當成產生程式碼的捷徑。我在一套結構化的工程流程中操作 AI agent，而我主要扮演架構師與系統設計者的角色。Agent 的產出只是提案：必須有依據、受約束並通過驗證，才能成為系統的一部分。",
    "how.ai.title": "Agent 負責",
    "how.ai.1": "專案評估",
    "how.ai.2": "需求分析",
    "how.ai.3": "架構規劃",
    "how.ai.4": "程式碼生成",
    "how.ai.5": "重構",
    "how.ai.6": "實作",
    "how.ai.7": "白箱測試",
    "how.ai.8": "黑箱測試",
    "how.ai.9": "整合測試",
    "how.ai.10": "可執行驗證",
    "how.ai.11": "技術文件",
    "how.ai.12": "長期專案記憶",
    "how.human.title": "我負責",
    "how.human.1": "架構",
    "how.human.2": "約束條件",
    "how.human.3": "取捨",
    "how.human.4": "驗收標準",
    "how.human.5": "風險",
    "how.human.6": "驗證",
    "how.human.7": "最終決策",
    "how.note": "在這套流程裡，AI 不是權威。它是一位工程執行者，產出必須像任何其他人的貢獻一樣被審查。",

    "wf.kicker": "流程",
    "wf.title": "端到端工程工作流程",
    "wf.lead": "從最初的可行性評估，到最後寫回長期記憶的內容，都走同一套流程。每個階段都會產出可被他人檢查的結果。",
    "wf.s1.t": "專案評估",
    "wf.s1.d": "界定範圍與可行性，並判斷這個問題是否值得以目前的形式解決。",
    "wf.s2.t": "證據蒐集",
    "wf.s2.d": "在做任何決策之前，先檢視程式碼庫、文件、schema、介面與執行時狀態。",
    "wf.s3.t": "架構與約束",
    "wf.s3.d": "系統邊界、不變條件、延遲預算與失效行為，由我定義並明確傳達給 agent。",
    "wf.s4.t": "實作規劃",
    "wf.s4.d": "拆解成足夠小的任務，使每一項都能單獨審查與驗證。",
    "wf.s5.t": "AI 輔助開發",
    "wf.s5.d": "在第三階段設定的約束之下，進行程式碼生成、重構與測試草稿。",
    "wf.s6.t": "可執行驗證",
    "wf.s6.d": "編譯器、測試套件、整合與黑箱測試、效能量測、執行時觀察、diff 審查。",
    "wf.s7.t": "實作後檢討",
    "wf.s7.d": "把結果對照驗收標準來檢查，而不是對照 agent 自己寫的工作摘要。",
    "wf.s8.t": "持久化知識更新",
    "wf.s8.d": "只有通過驗證的結論，才會寫回長期專案記憶。",
    "wf.sys1.t": "系統一 — 可靠性",
    "wf.sys1.d": "幻覺控制。讓 agent 以實際系統為依據，而不是依賴模型既有的假設。",
    "wf.sys1.link": "三層模型",
    "wf.sys2.t": "系統二 — 脈絡",
    "wf.sys2.d": "持久化記憶。避免知識在不同 session 之間流失，然後再花成本重新探索一次。",
    "wf.sys2.link": "語意記憶",

    "rel.kicker": "可靠性",
    "rel.title": "三層幻覺控制模型",
    "rel.lead": "這套做法無法消除幻覺。它的目的是降低風險，並讓沒有依據的主張能被及早發現 — 而且是由模型以外的東西發現。",
    "rel.l1.t": "以證據驅動的指令",
    "rel.l1.rule": "先檢視，再行動；先證據，再假設。",
    "rel.l1.d": "在實作之前，agent 被明確要求去檢視真實環境 — 程式碼、文件、介面、schema、執行時狀態與資料 — 並回報實際看到的內容。重要的是這套指令框架的機制，而不是背後某個 AI 產品的名稱。模型自身的知識，永遠不能被當成專案事實。",
    "rel.l2.t": "明確的事實來源",
    "rel.l2.rule": "「未知」是一個合法狀態。",
    "rel.l2.d": "執行過程會明確定義哪些來源具有權威性：專案程式碼、架構文件、API schema、規格、測試、執行時行為、真實資料集、已驗證的工程決策。每個陳述都帶有狀態標記，缺少的事實不會悄悄變成憑空捏造的假設。",
    "rel.l3.t": "可執行驗證",
    "rel.l3.rule": "主張不等於證明；執行結果才是證據。",
    "rel.l3.d": "Agent 說「這樣可以運作」並不構成任何證明。權威屬於可執行的系統與可觀察的結果，而不屬於模型對自己產出的解釋。",
    "rel.l3.m1": "整合測試",
    "rel.l3.m2": "白箱測試",
    "rel.l3.m3": "黑箱測試",
    "rel.l3.m4": "效能量測",
    "rel.l3.m5": "執行時觀察",
    "rel.l3.m6": "真實查詢與真實輸出",
    "rel.fig.cap": "圖 A — 一個主張如何成為已驗證的結果",
    "rel.fig.n1": "指令",
    "rel.fig.n2": "證據蒐集",
    "rel.fig.n3": "事實來源",
    "rel.fig.n4": "實作",
    "rel.fig.n5": "可執行驗證",

    "mem.kicker": "脈絡",
    "mem.title": "持久化語意記憶",
    "mem.lead": "長期專案會橫跨許多 session 與許多 agent 脈絡。我把工程知識放在以文件為基礎的外部記憶中，並以語意方式檢索，而不是每次都把整個知識庫塞進 session。",
    "mem.fig.cap": "圖 B — 檢索與寫回迴路",
    "mem.fig.n1": "Notion / Markdown 知識庫",
    "mem.fig.n2": "結構化專案文件",
    "mem.fig.n3": "切塊與向量化",
    "mem.fig.n4": "向量相似度檢索",
    "mem.fig.n5": "挑選相關脈絡",
    "mem.fig.n6": "注入 agent 脈絡",
    "mem.fig.n7": "開發 session",
    "mem.fig.n8": "已驗證的發現",
    "mem.fig.n9": "更新知識庫",
    "mem.holds.t": "記憶裡存放什麼",
    "mem.holds.1": "Notion 工作區與結構化 Markdown",
    "mem.holds.2": "專案與架構文件",
    "mem.holds.3": "決策紀錄",
    "mem.holds.4": "研究筆記與實作筆記",
    "mem.holds.5": "已驗證的發現",
    "mem.honest.t": "向量檢索能做什麼、不能做什麼",
    "mem.honest.d": "向量相似度並不保證內容正確。它改善的是檢索的相關性與脈絡精準度：讓 agent 看到語意上最相關的文件，而不是把整個知識庫不加篩選地倒進去。",
    "mem.reduce.t": "它可以減少：",
    "mem.reduce.1": "不相關的脈絡",
    "mem.reduce.2": "脈絡被稀釋",
    "mem.reduce.3": "跨 session 的知識流失",
    "mem.reduce.4": "重複探索同樣的事實",
    "mem.gate.t": "寫回的關卡",
    "mem.gate.d": "只有通過驗證的結論才能寫入持久化記憶。這道關卡避免一個幻覺被存進去之後，被之後每一個 session 當成既定事實再次取用。",
    "mem.gate.n1": "Agent 產出",
    "mem.gate.n2": "驗證",
    "mem.gate.n3": "已驗證知識",
    "mem.gate.n4": "持久化記憶",
    "mem.term.1": "以文件為基礎的外部記憶",
    "mem.term.2": "語意檢索",
    "mem.term.3": "持久化工程記憶",
    "mem.term.4": "RAG 式脈絡檢索",
    "mem.term.5": "向量相似度搜尋",
    "mem.term.6": "脈絡注入",

    "arch.kicker": "角色",
    "arch.title": "架構師主導的開發方式",
    "arch.lead": "我越來越多時間工作在架構與調度這一層，而不是逐行手寫每個實作細節。這是 AI 增強的工程方式 — 判斷、約束與責任仍然在我身上。",
    "arch.n1": "定義系統邊界",
    "arch.n2": "定義約束條件",
    "arch.n3": "拆解任務",
    "arch.n4": "委派給 agent",
    "arch.n5": "審查實作",
    "arch.n6": "驗證結果",
    "arch.n7": "整合知識",
    "arch.used.t": "已實際用於下列工程工作",
    "arch.used.1": "專案可行性評估",
    "arch.used.2": "既有系統分析",
    "arch.used.3": "軟體架構設計",
    "arch.used.4": "系統拆解",
    "arch.used.5": "實作規劃",
    "arch.used.6": "Rust 程式碼生成",
    "arch.used.7": "重構",
    "arch.used.8": "白箱測試",
    "arch.used.9": "黑箱測試",
    "arch.used.10": "整合測試",
    "arch.used.11": "除錯",
    "arch.used.12": "效能評估",
    "arch.used.13": "實作後檢討",
    "arch.used.14": "技術文件撰寫",
    "arch.tag.1": "AI 增強的工程",
    "arch.tag.2": "架構師主導的 agent 開發",
    "arch.tag.3": "以證據為基礎的 agent 工作流程",

    "proj.kicker": "實例",
    "proj.title": "AI 輔助工程案例",
    "proj.lead": "兩個以這套流程完成的 Rust 專案。兩個 repository 都是公開的，設計理由都寫在 README 裡。",
    "proj.repo": "程式碼庫",
    "proj.bg": "背景",
    "proj.decisions": "關鍵決策",
    "proj.tradeoff": "取捨原則",
    "proj.problem": "工程問題",
    "proj.outcome": "結果",
    "proj.myrole": "我的角色",
    "proj.airole": "Agent 的角色",
    "proj.stack": "技術",
    "proj.read": "延伸閱讀",

    "p1.tagline": "Rust 行情資料中介服務。來自一家頂尖交易公司面試流程中的 take-home 工程題目。",
    "p1.bg": "上游會持續送出跨多個商品的 <code>BookMessage</code> 訂單簿更新。這個服務必須維護每個商品的最新快照、提供 request/response 的快照查詢、即時推送給多個訂閱者、隔離慢速消費者，並確保慢速或斷線的客戶端不會影響 ingest 熱路徑 — 同時支援本機與遠端客戶端。傳輸方式、fan-out 行為、快照表示法與訂閱語意，題目刻意保留為工程設計決策。",
    "p1.d1.t": "非阻塞 ingest",
    "p1.d1.d": "熱路徑不會等待任何訂閱者。Fan-out 採非阻塞設計，因此慢速消費者無法對 ingest 造成反壓。",
    "p1.d2.t": "訂閱者隔離",
    "p1.d2.d": "每個訂閱者都有獨立的有界佇列。佇列滿時只對該訂閱者丟棄訊息，並以累計丟棄計數讓資料遺失變成可觀測，而不是悄悄發生。",
    "p1.d3.t": "清楚的抽象邊界",
    "p1.d3.d": "上游模擬器被放在 <code>Upstream</code> trait 之後，未來可換成真實的生產行情來源，而不需要改動服務的其他部分。",
    "p1.d4.t": "傳輸層",
    "p1.d4.d": "跨主機客戶端使用 HTTP/2 上的 gRPC：快照以 request/response 提供，訂閱以 server streaming 提供。",
    "p1.trade": "這個設計刻意優先考慮可預測性、故障隔離、正確性與維運安全，同時保持熱路徑的低延遲與非阻塞特性。",
    "p1.feedback": "在面試討論中，面試官形容這個設計是所有提交中「the safest」（最穩妥的）。我把它理解為一項刻意取捨的結果，而不是對哪份作業最好的評判：這是一個保守的架構，在低延遲、訂閱者隔離、明確的失效行為與維運安全之間取得平衡。",
    "p1.fig.cap": "Ingest 與 fan-out 路徑",
    "p1.fig.alt": "FeedSubscriber 送入 ingest loop，ingest loop 一方面將最新快照寫入 DashMap，一方面發布到 pub/sub bus，每個訂閱者各有一條有界佇列，最後透過 tonic gRPC 對外提供服務。",
    "p1.fig.snap": "最新快照",
    "p1.fig.bus": "pub/sub bus",
    "p1.fig.queue": "每訂閱者有界佇列",
    "p1.role": "系統設計、約束條件、延遲與失效需求，以及所有取捨決策。",
    "p1.ai": "解讀題目、探索架構方案、整理取捨、實作規劃、Rust 程式碼生成、測試規劃、審查輔助與驗證執行。",
    "p1.stack.1": "有界佇列",
    "p1.stack.2": "可重現的整合測試",
    "p1.link.assignment": "原始題目說明",
    "p1.link.impl": "實作與設計說明",

    "p2.tagline": "為 EdgeX 交易所串接而寫的 Rust 端 Stark 簽章相容層。",
    "p2.bg": "在 Binquant 進行 EdgeX 交易所串接時，該交易所要求使用 Stark 系列的密碼學簽章。當時可用的 Rust StarkNet 相關函式庫，無法產生與交易所認證流程相容的簽章。我在 AI 協助下研究其簽章演算法，並實作出串接所需的 Rust 端密碼學邏輯。",
    "p2.prob": "必須完整重現整條簽章流程：StarkCurve 橢圓曲線運算、Pedersen 雜湊、訂單雜湊建構、確定性簽章、L2 訂單欄位、手續費計算與金鑰推導 — 每一步都要與交易所逐位元一致，因為簽章只有被接受與不被接受兩種結果。",
    "p2.outcome": "一份可運作的 Rust 實作，能產生交易所接受的簽章，並整合進交易系統的交易所連線流程。",
    "p2.note": "這是一個實作與相容性解決方案。StarkCurve、Pedersen 雜湊與 StarkNet 簽章機制都是既有設計；這個專案的工作是在 Rust 中正確地重現它們。",
    "p2.impl.t": "已實作的元件",
    "p2.impl.1": "Pedersen 雜湊",
    "p2.impl.2": "限價單雜湊",
    "p2.impl.3": "StarkNet 形式的簽章",
    "p2.impl.4": "L2 訂單欄位建構",
    "p2.impl.5": "私鑰推導",
    "p2.ai": "研究規格、比對不同實作、把演算法概念轉譯為 Rust、除錯相容性問題、產生實作骨架，以及用已知數值驗證中間計算結果。",
    "p2.role": "定義正確性需求、驗證與交易所的相容性、審查密碼學行為，並將成果整合進交易系統。",

    "princ.kicker": "原則",
    "princ.title": "工程原則",
    "princ.1": "先有證據，再談假設。",
    "princ.2": "承認未知，好過編造答案。",
    "princ.3": "AI 的產出是提案，不是權威。",
    "princ.4": "可執行的結果，勝過任何解釋。",
    "princ.5": "只有已驗證的知識才能成為持久記憶。",
    "princ.6": "架構與約束始終是人的責任。",
    "princ.7": "要優化的是脈絡品質，不是脈絡數量。",

    "foot.role": "Rust 系統與交易基礎設施工程",
    "foot.note": "純靜態頁面，無框架、無建置流程。"
  };

  I18N["zh-CN"] = {
    "meta.title": "Jory — AI 辅助系统工程工作流",
    "meta.desc": "以证据为基础的 AI 辅助软件工程、持久化语义记忆、可执行验证、Rust 系统与交易基础设施。",

    "a11y.skip": "跳至主要内容",
    "a11y.menu": "打开菜单",
    "a11y.nav": "主导航",
    "a11y.lang": "语言",

    "nav.brandsub": "AI 辅助系统工程",
    "nav.how": "方法",
    "nav.workflow": "工作流",
    "nav.reliability": "可靠性",
    "nav.memory": "记忆",
    "nav.projects": "项目",

    "hero.eyebrow": "Rust 系统与交易基础设施",
    "hero.title": "以架构师为主导的 AI 辅助工程",
    "hero.sub": "以证据为基础的 AI agent、持久化语义记忆、可执行验证，以及面向生产环境的工程实践。",
    "hero.cta1": "查看工作流",
    "hero.cta2": "前往 GitHub",
    "hero.record.title": "验证记录",
    "hero.record.note": "格式示例",
    "hero.record.k1": "主张",
    "hero.record.v1": "agent 声称 fan-out 不会阻塞 ingest",
    "hero.record.k2": "事实来源",
    "hero.record.v2": "项目代码 + 集成测试",
    "hero.record.k3": "验证方式",
    "hero.record.v3": "cargo test — 实际执行并观察结果",
    "hero.record.k4": "状态",
    "hero.record.foot": "少了第三行，第一行就只是一个未经证实的说法。",

    "how.kicker": "定位",
    "how.title": "我如何使用 AI",
    "how.lead": "我不把 AI 当成生成代码的捷径。我在一套结构化的工程流程中驱动 AI agent，而我主要扮演架构师与系统设计者的角色。Agent 的产出只是提案：必须有依据、受约束并通过验证，才能成为系统的一部分。",
    "how.ai.title": "Agent 负责",
    "how.ai.1": "项目评估",
    "how.ai.2": "需求分析",
    "how.ai.3": "架构规划",
    "how.ai.4": "代码生成",
    "how.ai.5": "重构",
    "how.ai.6": "实现",
    "how.ai.7": "白盒测试",
    "how.ai.8": "黑盒测试",
    "how.ai.9": "集成测试",
    "how.ai.10": "可执行验证",
    "how.ai.11": "技术文档",
    "how.ai.12": "长期项目记忆",
    "how.human.title": "我负责",
    "how.human.1": "架构",
    "how.human.2": "约束条件",
    "how.human.3": "取舍",
    "how.human.4": "验收标准",
    "how.human.5": "风险",
    "how.human.6": "验证",
    "how.human.7": "最终决策",
    "how.note": "在这套流程里，AI 不是权威。它是一位工程执行者，产出必须像任何其他人的贡献一样被评审。",

    "wf.kicker": "流程",
    "wf.title": "端到端工程工作流",
    "wf.lead": "从最初的可行性评估，到最后写回长期记忆的内容，都走同一套流程。每个阶段都会产出可被他人检查的结果。",
    "wf.s1.t": "项目评估",
    "wf.s1.d": "界定范围与可行性，并判断这个问题是否值得以当前的形式去解决。",
    "wf.s2.t": "证据收集",
    "wf.s2.d": "在做任何决策之前，先检视代码库、文档、schema、接口与运行时状态。",
    "wf.s3.t": "架构与约束",
    "wf.s3.d": "系统边界、不变式、延迟预算与失效行为，由我定义并明确传达给 agent。",
    "wf.s4.t": "实现规划",
    "wf.s4.d": "拆解成足够小的任务，使每一项都能单独评审与验证。",
    "wf.s5.t": "AI 辅助开发",
    "wf.s5.d": "在第三阶段设定的约束之下，进行代码生成、重构与测试草稿。",
    "wf.s6.t": "可执行验证",
    "wf.s6.d": "编译器、测试套件、集成与黑盒测试、性能测量、运行时观察、diff 评审。",
    "wf.s7.t": "实现后复盘",
    "wf.s7.d": "把结果对照验收标准来检查，而不是对照 agent 自己写的工作总结。",
    "wf.s8.t": "持久化知识更新",
    "wf.s8.d": "只有通过验证的结论，才会写回长期项目记忆。",
    "wf.sys1.t": "系统一 — 可靠性",
    "wf.sys1.d": "幻觉控制。让 agent 以真实系统为依据，而不是依赖模型已有的假设。",
    "wf.sys1.link": "三层模型",
    "wf.sys2.t": "系统二 — 上下文",
    "wf.sys2.d": "持久化记忆。避免知识在不同会话之间流失，之后又要花成本重新探索一次。",
    "wf.sys2.link": "语义记忆",

    "rel.kicker": "可靠性",
    "rel.title": "三层幻觉控制模型",
    "rel.lead": "这套做法无法消除幻觉。它的目的是降低风险，并让没有依据的主张能被尽早发现 — 而且是由模型以外的东西发现。",
    "rel.l1.t": "以证据驱动的指令",
    "rel.l1.rule": "先检视，再行动；先证据，再假设。",
    "rel.l1.d": "在实现之前，agent 被明确要求去检视真实环境 — 代码、文档、接口、schema、运行时状态与数据 — 并回报实际看到的内容。重要的是这套指令框架的机制，而不是背后某个 AI 产品的名称。模型自身的知识，永远不能被当成项目事实。",
    "rel.l2.t": "明确的事实来源",
    "rel.l2.rule": "“未知”是一个合法状态。",
    "rel.l2.d": "执行过程会明确定义哪些来源具有权威性：项目代码、架构文档、API schema、规格、测试、运行时行为、真实数据集、已验证的工程决策。每个陈述都带有状态标记，缺失的事实不会悄悄变成凭空编造的假设。",
    "rel.l3.t": "可执行验证",
    "rel.l3.rule": "主张不等于证明；执行结果才是证据。",
    "rel.l3.d": "Agent 说“这样可以正常工作”并不构成任何证明。权威属于可执行的系统与可观察的结果，而不属于模型对自己产出的解释。",
    "rel.l3.m1": "集成测试",
    "rel.l3.m2": "白盒测试",
    "rel.l3.m3": "黑盒测试",
    "rel.l3.m4": "性能测量",
    "rel.l3.m5": "运行时观察",
    "rel.l3.m6": "真实查询与真实输出",
    "rel.fig.cap": "图 A — 一个主张如何成为已验证的结果",
    "rel.fig.n1": "指令",
    "rel.fig.n2": "证据收集",
    "rel.fig.n3": "事实来源",
    "rel.fig.n4": "实现",
    "rel.fig.n5": "可执行验证",

    "mem.kicker": "上下文",
    "mem.title": "持久化语义记忆",
    "mem.lead": "长期项目会跨越许多会话与许多 agent 上下文。我把工程知识放在以文档为基础的外部记忆中，并以语义方式检索，而不是每次都把整个知识库塞进会话。",
    "mem.fig.cap": "图 B — 检索与写回闭环",
    "mem.fig.n1": "Notion / Markdown 知识库",
    "mem.fig.n2": "结构化项目文档",
    "mem.fig.n3": "分块与向量化",
    "mem.fig.n4": "向量相似度检索",
    "mem.fig.n5": "筛选相关上下文",
    "mem.fig.n6": "注入 agent 上下文",
    "mem.fig.n7": "开发会话",
    "mem.fig.n8": "已验证的结论",
    "mem.fig.n9": "更新知识库",
    "mem.holds.t": "记忆里存放什么",
    "mem.holds.1": "Notion 工作区与结构化 Markdown",
    "mem.holds.2": "项目与架构文档",
    "mem.holds.3": "决策记录",
    "mem.holds.4": "研究笔记与实现笔记",
    "mem.holds.5": "已验证的结论",
    "mem.honest.t": "向量检索能做什么、不能做什么",
    "mem.honest.d": "向量相似度并不保证内容正确。它改善的是检索相关性与上下文精度：让 agent 看到语义上最相关的文档，而不是把整个知识库不加筛选地倒进去。",
    "mem.reduce.t": "它可以减少：",
    "mem.reduce.1": "无关的上下文",
    "mem.reduce.2": "上下文被稀释",
    "mem.reduce.3": "跨会话的知识流失",
    "mem.reduce.4": "重复探索同样的事实",
    "mem.gate.t": "写回的关卡",
    "mem.gate.d": "只有通过验证的结论才能写入持久化记忆。这道关卡避免一个幻觉被存进去之后，被之后每一个会话当成既定事实反复取用。",
    "mem.gate.n1": "Agent 产出",
    "mem.gate.n2": "验证",
    "mem.gate.n3": "已验证知识",
    "mem.gate.n4": "持久化记忆",
    "mem.term.1": "以文档为基础的外部记忆",
    "mem.term.2": "语义检索",
    "mem.term.3": "持久化工程记忆",
    "mem.term.4": "RAG 式上下文检索",
    "mem.term.5": "向量相似度搜索",
    "mem.term.6": "上下文注入",

    "arch.kicker": "角色",
    "arch.title": "架构师主导的开发方式",
    "arch.lead": "我越来越多时间工作在架构与编排这一层，而不是逐行手写每个实现细节。这是 AI 增强的工程方式 — 判断、约束与责任仍然在我身上。",
    "arch.n1": "定义系统边界",
    "arch.n2": "定义约束条件",
    "arch.n3": "拆解任务",
    "arch.n4": "委派给 agent",
    "arch.n5": "评审实现",
    "arch.n6": "验证结果",
    "arch.n7": "整合知识",
    "arch.used.t": "已实际用于以下工程工作",
    "arch.used.1": "项目可行性评估",
    "arch.used.2": "遗留系统分析",
    "arch.used.3": "软件架构设计",
    "arch.used.4": "系统拆解",
    "arch.used.5": "实现规划",
    "arch.used.6": "Rust 代码生成",
    "arch.used.7": "重构",
    "arch.used.8": "白盒测试",
    "arch.used.9": "黑盒测试",
    "arch.used.10": "集成测试",
    "arch.used.11": "调试",
    "arch.used.12": "性能评估",
    "arch.used.13": "实现后复盘",
    "arch.used.14": "技术文档撰写",
    "arch.tag.1": "AI 增强的工程",
    "arch.tag.2": "架构师主导的 agent 开发",
    "arch.tag.3": "以证据为基础的 agent 工作流",

    "proj.kicker": "实例",
    "proj.title": "AI 辅助工程案例",
    "proj.lead": "两个用这套流程完成的 Rust 项目。两个仓库都是公开的，设计理由都写在 README 里。",
    "proj.repo": "代码仓库",
    "proj.bg": "背景",
    "proj.decisions": "关键决策",
    "proj.tradeoff": "取舍原则",
    "proj.problem": "工程问题",
    "proj.outcome": "结果",
    "proj.myrole": "我的角色",
    "proj.airole": "Agent 的角色",
    "proj.stack": "技术栈",
    "proj.read": "延伸阅读",

    "p1.tagline": "Rust 行情数据中间件。来自一家顶尖交易公司面试流程中的 take-home 工程题目。",
    "p1.bg": "上游会持续推送跨多个标的的 <code>BookMessage</code> 订单簿更新。该服务需要维护每个标的的最新快照、提供 request/response 的快照查询、实时推送给多个订阅者、隔离慢速消费者，并确保慢速或断连的客户端不会影响 ingest 热路径 — 同时支持本地与远程客户端。传输方式、fan-out 行为、快照表示法与订阅语义，题目刻意留作工程设计决策。",
    "p1.d1.t": "非阻塞 ingest",
    "p1.d1.d": "热路径不会等待任何订阅者。Fan-out 采用非阻塞设计，因此慢速消费者无法对 ingest 形成反压。",
    "p1.d2.t": "订阅者隔离",
    "p1.d2.d": "每个订阅者都有独立的有界队列。队列写满时只对该订阅者丢弃消息，并以累计丢弃计数让数据丢失变得可观测，而不是悄悄发生。",
    "p1.d3.t": "清晰的抽象边界",
    "p1.d3.d": "上游模拟器被放在 <code>Upstream</code> trait 之后，将来可换成真实的生产行情源，而无需改动服务的其他部分。",
    "p1.d4.t": "传输层",
    "p1.d4.d": "跨主机客户端使用 HTTP/2 上的 gRPC：快照以 request/response 提供，订阅以 server streaming 提供。",
    "p1.trade": "这个设计刻意优先考虑可预测性、故障隔离、正确性与运维安全，同时保持热路径的低延迟与非阻塞特性。",
    "p1.feedback": "在面试讨论中，面试官形容这个设计是所有提交中“the safest”（最稳妥的）。我把它理解为一次刻意取舍的结果，而不是对哪份作业最好的评判：这是一个保守的架构，在低延迟、订阅者隔离、明确的失效行为与运维安全之间取得平衡。",
    "p1.fig.cap": "Ingest 与 fan-out 路径",
    "p1.fig.alt": "FeedSubscriber 送入 ingest loop，ingest loop 一方面将最新快照写入 DashMap，一方面发布到 pub/sub bus，每个订阅者各有一条有界队列，最后通过 tonic gRPC 对外提供服务。",
    "p1.fig.snap": "最新快照",
    "p1.fig.bus": "pub/sub bus",
    "p1.fig.queue": "每订阅者有界队列",
    "p1.role": "系统设计、约束条件、延迟与失效需求，以及所有取舍决策。",
    "p1.ai": "解读题目、探索架构方案、梳理取舍、实现规划、Rust 代码生成、测试规划、评审辅助与验证执行。",
    "p1.stack.1": "有界队列",
    "p1.stack.2": "可重现的集成测试",
    "p1.link.assignment": "原始题目说明",
    "p1.link.impl": "实现与设计说明",

    "p2.tagline": "为 EdgeX 交易所对接而写的 Rust 端 Stark 签名兼容层。",
    "p2.bg": "在 Binquant 做 EdgeX 交易所对接时，该交易所要求使用 Stark 系列的密码学签名。当时可用的 Rust StarkNet 相关库，无法产生与交易所认证流程兼容的签名。我在 AI 协助下研究了签名算法，并实现了对接所需的 Rust 端密码学逻辑。",
    "p2.prob": "需要完整复现整条签名流水线：StarkCurve 椭圆曲线运算、Pedersen 哈希、订单哈希构造、确定性签名、L2 订单字段、手续费计算与密钥派生 — 每一步都要与交易所逐字节一致，因为签名只有被接受与不被接受两种结果。",
    "p2.outcome": "一份可用的 Rust 实现，能产生交易所接受的签名，并集成进交易系统的交易所连接流程。",
    "p2.note": "这是一个实现与兼容性解决方案。StarkCurve、Pedersen 哈希与 StarkNet 签名机制都是既有设计；这个项目的工作是在 Rust 中正确地复现它们。",
    "p2.impl.t": "已实现的组件",
    "p2.impl.1": "Pedersen 哈希",
    "p2.impl.2": "限价单哈希",
    "p2.impl.3": "StarkNet 形式的签名",
    "p2.impl.4": "L2 订单字段构造",
    "p2.impl.5": "私钥派生",
    "p2.ai": "研究规格、比对不同实现、把算法概念转译为 Rust、调试兼容性问题、生成实现骨架，以及用已知数值校验中间计算结果。",
    "p2.role": "定义正确性需求、验证与交易所的兼容性、评审密码学行为，并将成果集成进交易系统。",

    "princ.kicker": "原则",
    "princ.title": "工程原则",
    "princ.1": "先有证据，再谈假设。",
    "princ.2": "承认未知，好过编造答案。",
    "princ.3": "AI 的产出是提案，不是权威。",
    "princ.4": "可执行的结果，胜过任何解释。",
    "princ.5": "只有已验证的知识才能成为持久记忆。",
    "princ.6": "架构与约束始终是人的责任。",
    "princ.7": "要优化的是上下文质量，而不是上下文数量。",

    "foot.role": "Rust 系统与交易基础设施工程",
    "foot.note": "纯静态页面，无框架、无构建流程。"
  };

  I18N["fr"] = {
    "meta.title": "Jory — Ingénierie système assistée par IA",
    "meta.desc": "Ingénierie logicielle assistée par IA et fondée sur les preuves : mémoire sémantique persistante, vérification exécutable, systèmes Rust et infrastructure de trading.",

    "a11y.skip": "Aller au contenu",
    "a11y.menu": "Ouvrir le menu",
    "a11y.nav": "Navigation principale",
    "a11y.lang": "Langue",

    "nav.brandsub": "Ingénierie système assistée par IA",
    "nav.how": "Approche",
    "nav.workflow": "Processus",
    "nav.reliability": "Fiabilité",
    "nav.memory": "Mémoire",
    "nav.projects": "Projets",

    "hero.eyebrow": "Systèmes Rust et infrastructure de trading",
    "hero.title": "Ingénierie assistée par IA, pilotée par l'architecte",
    "hero.sub": "Des agents fondés sur les preuves, une mémoire sémantique persistante, une vérification exécutable et une ingénierie orientée production.",
    "hero.cta1": "Voir le processus",
    "hero.cta2": "Voir GitHub",
    "hero.record.title": "fiche de vérification",
    "hero.record.note": "modèle",
    "hero.record.k1": "affirmation",
    "hero.record.v1": "l'agent affirme que la diffusion ne bloque jamais l'ingestion",
    "hero.record.k2": "source de vérité",
    "hero.record.v2": "code du dépôt + test d'intégration",
    "hero.record.k3": "vérification",
    "hero.record.v3": "cargo test — exécuté et observé",
    "hero.record.k4": "état",
    "hero.record.foot": "Sans la troisième ligne, la première n'est qu'une affirmation.",

    "how.kicker": "positionnement",
    "how.title": "Comment j'utilise l'IA",
    "how.lead": "Je ne considère pas l'IA comme un raccourci pour produire du code. Je pilote des agents à l'intérieur d'un processus d'ingénierie structuré, et j'y travaille avant tout comme architecte et concepteur système. La sortie d'un agent est une proposition : elle doit être étayée, contrainte et vérifiée avant d'entrer dans un système.",
    "how.ai.title": "L'agent prend en charge",
    "how.ai.1": "L'évaluation du projet",
    "how.ai.2": "L'analyse des besoins",
    "how.ai.3": "La planification de l'architecture",
    "how.ai.4": "La génération de code",
    "how.ai.5": "Le refactoring",
    "how.ai.6": "L'implémentation",
    "how.ai.7": "Les tests boîte blanche",
    "how.ai.8": "Les tests boîte noire",
    "how.ai.9": "Les tests d'intégration",
    "how.ai.10": "La validation exécutable",
    "how.ai.11": "La documentation",
    "how.ai.12": "La mémoire de projet à long terme",
    "how.human.title": "Je reste responsable de",
    "how.human.1": "L'architecture",
    "how.human.2": "Les contraintes",
    "how.human.3": "Les compromis",
    "how.human.4": "Les critères d'acceptation",
    "how.human.5": "Le risque",
    "how.human.6": "La vérification",
    "how.human.7": "Les décisions finales",
    "how.note": "Dans ce processus, l'IA n'est pas une autorité. C'est un exécutant technique dont la production est relue comme n'importe quelle autre contribution.",

    "wf.kicker": "processus",
    "wf.title": "Processus d'ingénierie de bout en bout",
    "wf.lead": "La même séquence va de la première lecture de faisabilité jusqu'à ce qui sera réécrit dans la mémoire à long terme. Chaque étape produit un résultat qu'une autre personne peut contrôler.",
    "wf.s1.t": "Évaluation du projet",
    "wf.s1.d": "Périmètre, faisabilité, et pertinence du problème sous la forme dans laquelle il se présente.",
    "wf.s2.t": "Collecte de preuves",
    "wf.s2.d": "Inspecter le dépôt, la documentation, les schémas, les interfaces et l'état d'exécution avant toute décision.",
    "wf.s3.t": "Architecture et contraintes",
    "wf.s3.d": "Frontières, invariants, budget de latence et comportement en cas de panne : définis par moi, énoncés explicitement à l'agent.",
    "wf.s4.t": "Planification de l'implémentation",
    "wf.s4.d": "Découpage en tâches assez petites pour être relues et vérifiées une par une.",
    "wf.s5.t": "Développement assisté par IA",
    "wf.s5.d": "Génération de code, refactoring et rédaction des tests, dans les limites fixées à l'étape trois.",
    "wf.s6.t": "Vérification exécutable",
    "wf.s6.d": "Compilateur, suites de tests, exécutions d'intégration et boîte noire, benchmarks, observation à l'exécution, relecture du diff.",
    "wf.s7.t": "Revue post-implémentation",
    "wf.s7.d": "Comparer le résultat aux critères d'acceptation, et non au résumé que l'agent fait de son propre travail.",
    "wf.s8.t": "Mise à jour de la mémoire",
    "wf.s8.d": "Seules les conclusions vérifiées sont réécrites dans la mémoire de projet à long terme.",
    "wf.sys1.t": "Premier système — fiabilité",
    "wf.sys1.d": "Contrôle des hallucinations. Maintient l'agent ancré dans le système réel plutôt que dans les a priori du modèle.",
    "wf.sys1.link": "Le modèle à trois couches",
    "wf.sys2.t": "Second système — contexte",
    "wf.sys2.d": "Mémoire persistante. Évite que la connaissance se perde entre deux sessions puis soit redécouverte à grands frais.",
    "wf.sys2.link": "La mémoire sémantique",

    "rel.kicker": "fiabilité",
    "rel.title": "Contrôle des hallucinations en trois couches",
    "rel.lead": "Cela n'élimine pas les hallucinations. L'objectif est d'en réduire le risque et de rendre les affirmations non étayées faciles à repérer — tôt, et par autre chose que le modèle lui-même.",
    "rel.l1.t": "Instruction fondée sur les preuves",
    "rel.l1.rule": "Inspecter avant d'agir. Des preuves avant des hypothèses.",
    "rel.l1.d": "Avant toute implémentation, l'agent a pour consigne d'inspecter l'environnement réel — code, documentation, interfaces, schémas, état d'exécution, données — et de rapporter ce qu'il y a trouvé. C'est le cadre d'instruction qui compte, pas le nom du produit qui le porte. La connaissance du modèle ne tient jamais lieu de vérité projet.",
    "rel.l2.t": "Source de vérité explicite",
    "rel.l2.rule": "« Inconnu » est un état valide.",
    "rel.l2.d": "L'exécution définit quelles sources font autorité : code du dépôt, documents d'architecture, schémas d'API, spécifications, tests, comportement à l'exécution, jeux de données réels, décisions d'ingénierie vérifiées. Chaque énoncé porte un état, de sorte qu'un fait manquant ne devient jamais discrètement une hypothèse inventée.",
    "rel.l3.t": "Vérification exécutable",
    "rel.l3.rule": "Une affirmation n'est pas une preuve. Un résultat d'exécution en est une.",
    "rel.l3.d": "Un agent qui déclare que quelque chose fonctionne ne prouve rien. L'autorité appartient aux systèmes exécutables et aux résultats observables, pas à l'explication que le modèle donne de sa propre sortie.",
    "rel.l3.m1": "tests d'intégration",
    "rel.l3.m2": "tests boîte blanche",
    "rel.l3.m3": "tests boîte noire",
    "rel.l3.m4": "benchmarks",
    "rel.l3.m5": "observation à l'exécution",
    "rel.l3.m6": "requêtes et sorties réelles",
    "rel.fig.cap": "Schéma A — comment une affirmation devient un résultat vérifié",
    "rel.fig.n1": "Instruction",
    "rel.fig.n2": "Collecte de preuves",
    "rel.fig.n3": "Source de vérité",
    "rel.fig.n4": "Implémentation",
    "rel.fig.n5": "Vérification exécutable",

    "mem.kicker": "contexte",
    "mem.title": "Mémoire sémantique persistante",
    "mem.lead": "Un projet long s'étale sur de nombreuses sessions et de nombreux contextes d'agent. Je conserve la connaissance d'ingénierie dans une mémoire externe adossée à des documents, et je la récupère par similarité sémantique plutôt que de recharger toute la base à chaque session.",
    "mem.fig.cap": "Schéma B — boucle de récupération et de réécriture",
    "mem.fig.n1": "Base de connaissances Notion / Markdown",
    "mem.fig.n2": "Documents de projet structurés",
    "mem.fig.n3": "Découpage et embeddings",
    "mem.fig.n4": "Récupération par similarité vectorielle",
    "mem.fig.n5": "Sélection du contexte pertinent",
    "mem.fig.n6": "Injection dans le contexte de l'agent",
    "mem.fig.n7": "Session de développement",
    "mem.fig.n8": "Conclusions vérifiées",
    "mem.fig.n9": "Mise à jour de la base",
    "mem.holds.t": "Ce que contient la mémoire",
    "mem.holds.1": "Espace Notion et Markdown structuré",
    "mem.holds.2": "Documentation de projet et d'architecture",
    "mem.holds.3": "Registres de décisions",
    "mem.holds.4": "Notes de recherche et d'implémentation",
    "mem.holds.5": "Conclusions vérifiées",
    "mem.honest.t": "Ce que la recherche vectorielle fait, et ne fait pas",
    "mem.honest.d": "La similarité vectorielle ne garantit pas la justesse. Elle améliore la pertinence de la récupération et la précision du contexte : l'agent voit les documents sémantiquement les plus proches, au lieu d'un déversement indifférencié de toute la base.",
    "mem.reduce.t": "Elle réduit :",
    "mem.reduce.1": "Le contexte hors sujet",
    "mem.reduce.2": "La dilution du contexte",
    "mem.reduce.3": "La perte de connaissance entre sessions",
    "mem.reduce.4": "La redécouverte répétée des mêmes faits",
    "mem.gate.t": "Le filtre de réécriture",
    "mem.gate.d": "Seules les conclusions vérifiées sont promues en mémoire persistante. C'est ce qui empêche une hallucination d'être stockée une fois puis relue comme un fait établi par toutes les sessions suivantes.",
    "mem.gate.n1": "Sortie de l'agent",
    "mem.gate.n2": "Vérification",
    "mem.gate.n3": "Connaissance vérifiée",
    "mem.gate.n4": "Mémoire persistante",
    "mem.term.1": "Mémoire externe adossée aux documents",
    "mem.term.2": "Récupération sémantique",
    "mem.term.3": "Mémoire d'ingénierie persistante",
    "mem.term.4": "Récupération de contexte de type RAG",
    "mem.term.5": "Recherche par similarité vectorielle",
    "mem.term.6": "Injection de contexte",

    "arch.kicker": "rôle",
    "arch.title": "Développement piloté par l'architecte",
    "arch.lead": "Je travaille de plus en plus au niveau de l'architecture et de l'orchestration, plutôt que d'écrire à la main chaque détail d'implémentation. C'est une ingénierie augmentée par l'IA : le jugement, les contraintes et la responsabilité restent de mon côté.",
    "arch.n1": "Définir les frontières du système",
    "arch.n2": "Définir les contraintes",
    "arch.n3": "Découper les tâches",
    "arch.n4": "Déléguer aux agents",
    "arch.n5": "Relire l'implémentation",
    "arch.n6": "Vérifier les résultats",
    "arch.n7": "Intégrer la connaissance",
    "arch.used.t": "Utilisé sur des travaux d'ingénierie réels",
    "arch.used.1": "Évaluation de faisabilité",
    "arch.used.2": "Analyse de système existant",
    "arch.used.3": "Architecture logicielle",
    "arch.used.4": "Décomposition système",
    "arch.used.5": "Planification d'implémentation",
    "arch.used.6": "Génération de code Rust",
    "arch.used.7": "Refactoring",
    "arch.used.8": "Tests boîte blanche",
    "arch.used.9": "Tests boîte noire",
    "arch.used.10": "Tests d'intégration",
    "arch.used.11": "Débogage",
    "arch.used.12": "Évaluation de performance",
    "arch.used.13": "Revue post-implémentation",
    "arch.used.14": "Documentation technique",
    "arch.tag.1": "Ingénierie augmentée par l'IA",
    "arch.tag.2": "Développement par agents piloté par l'architecte",
    "arch.tag.3": "Processus d'agents fondé sur les preuves",

    "proj.kicker": "cas concrets",
    "proj.title": "Études de cas en ingénierie assistée par IA",
    "proj.lead": "Deux projets Rust construits avec ce processus. Les deux dépôts sont publics ; le raisonnement est dans les README.",
    "proj.repo": "Dépôt",
    "proj.bg": "Contexte",
    "proj.decisions": "Décisions clés",
    "proj.tradeoff": "Philosophie des compromis",
    "proj.problem": "Problème d'ingénierie",
    "proj.outcome": "Résultat",
    "proj.myrole": "Mon rôle",
    "proj.airole": "Le rôle de l'agent",
    "proj.stack": "Technologies",
    "proj.read": "Pour aller plus loin",

    "p1.tagline": "Middleware de données de marché en Rust. Exercice d'ingénierie à rendre, proposé par une grande société de trading.",
    "p1.bg": "L'amont émet un flux continu de mises à jour de carnet d'ordres <code>BookMessage</code> sur de nombreux instruments. Le service doit maintenir le dernier instantané par instrument, offrir un accès requête/réponse à ces instantanés, publier les mises à jour en temps réel vers de nombreux abonnés, isoler les consommateurs lents et tenir les clients lents ou déconnectés à l'écart du chemin critique d'ingestion — pour des clients locaux comme distants. Le transport, le comportement de diffusion, la représentation des instantanés et la sémantique d'abonnement étaient délibérément laissés à la décision d'ingénierie.",
    "p1.d1.t": "Ingestion non bloquante",
    "p1.d1.d": "Le chemin critique n'attend jamais les abonnés. La diffusion est non bloquante : un consommateur lent ne peut pas exercer de contre-pression sur l'ingestion.",
    "p1.d2.t": "Isolation des abonnés",
    "p1.d2.d": "Chaque abonné dispose d'une file bornée indépendante. Quand elle se remplit, les messages ne sont perdus que pour cet abonné, et un compteur cumulé de messages abandonnés rend la perte observable au lieu de silencieuse.",
    "p1.d3.t": "Frontière d'abstraction nette",
    "p1.d3.d": "Le simulateur amont se trouve derrière un trait <code>Upstream</code> : la vraie source de production peut le remplacer sans toucher au reste du service.",
    "p1.d4.t": "Transport",
    "p1.d4.d": "gRPC sur HTTP/2 pour les clients distants : requête/réponse pour les instantanés, streaming serveur pour les abonnements.",
    "p1.trade": "La conception privilégie délibérément la prévisibilité, l'isolation des pannes, la correction et la sûreté d'exploitation, tout en gardant un chemin critique non bloquant et à faible latence.",
    "p1.feedback": "Lors de l'entretien, l'examinateur a décrit la conception comme « the safest » (la plus sûre) parmi les soumissions. Je l'interprète comme le résultat d'un compromis assumé, et non comme un verdict sur la meilleure soumission : une architecture conservatrice qui équilibre faible latence, isolation des abonnés, comportement d'échec explicite et sûreté d'exploitation.",
    "p1.fig.cap": "Chemin d'ingestion et de diffusion",
    "p1.fig.alt": "FeedSubscriber alimente la boucle d'ingestion, qui écrit les derniers instantanés dans une DashMap et publie sur un bus pub/sub doté d'une file bornée par abonné, exposé via tonic gRPC.",
    "p1.fig.snap": "derniers instantanés",
    "p1.fig.bus": "bus pub/sub",
    "p1.fig.queue": "file bornée par abonné",
    "p1.role": "Conception du système, contraintes, exigences de latence et de comportement en panne, et chacun des compromis.",
    "p1.ai": "Interprétation de l'énoncé, exploration d'architectures, mise à plat des compromis, planification, génération de code Rust, plan de tests, aide à la relecture, exécutions de vérification.",
    "p1.stack.1": "files bornées",
    "p1.stack.2": "tests d'intégration déterministes",
    "p1.link.assignment": "Énoncé d'origine",
    "p1.link.impl": "Notes d'implémentation et de conception",

    "p2.tagline": "Une couche de compatibilité Rust pour la signature Stark, écrite pour une intégration de l'exchange EdgeX.",
    "p2.bg": "En construisant l'intégration de l'exchange EdgeX chez Binquant, l'exchange exigeait une signature cryptographique de type Stark. Les bibliothèques Rust liées à StarkNet disponibles à l'époque ne produisaient pas de signatures compatibles avec le flux d'authentification exigé. Avec l'aide de l'IA, j'ai étudié l'algorithme de signature et implémenté la logique cryptographique nécessaire côté Rust.",
    "p2.prob": "Reproduire toute la chaîne de signature : opérations sur la courbe elliptique StarkCurve, hachage Pedersen, construction du hash d'ordre, signature déterministe, champs d'ordre L2, calcul des frais et dérivation de clé — chaque étape devant correspondre octet pour octet, puisqu'une signature est acceptée ou ne l'est pas.",
    "p2.outcome": "Une implémentation Rust fonctionnelle qui produit des signatures acceptées par l'exchange, intégrée au flux de connectivité du système de trading.",
    "p2.note": "Il s'agit d'une solution d'implémentation et de compatibilité. StarkCurve, le hachage Pedersen et le schéma de signature StarkNet sont des conceptions existantes ; le travail consiste à les reproduire correctement en Rust.",
    "p2.impl.t": "Composants implémentés",
    "p2.impl.1": "hachage Pedersen",
    "p2.impl.2": "hash d'ordre à cours limité",
    "p2.impl.3": "signature de type StarkNet",
    "p2.impl.4": "construction des champs d'ordre L2",
    "p2.impl.5": "dérivation de clé privée",
    "p2.ai": "Étude des spécifications, comparaison d'implémentations, traduction des concepts algorithmiques en Rust, débogage des incompatibilités, génération d'ossature d'implémentation, validation des calculs intermédiaires par rapport à des valeurs connues.",
    "p2.role": "Définir les exigences de correction, vérifier la compatibilité avec l'exchange, relire le comportement cryptographique et intégrer le résultat au système de trading.",

    "princ.kicker": "principes",
    "princ.title": "Principes d'ingénierie",
    "princ.1": "Les preuves avant les hypothèses.",
    "princ.2": "Mieux vaut inconnu qu'inventé.",
    "princ.3": "La sortie d'une IA est une proposition, pas une autorité.",
    "princ.4": "Un résultat exécutable prime sur une explication.",
    "princ.5": "Seule la connaissance vérifiée entre en mémoire persistante.",
    "princ.6": "L'architecture et les contraintes restent des responsabilités humaines.",
    "princ.7": "Optimiser la qualité du contexte, pas sa quantité.",

    "foot.role": "Ingénierie de systèmes Rust et d'infrastructure de trading",
    "foot.note": "Page statique. Sans framework, sans étape de build."
  };

  /* ── apply ─────────────────────────────────────────────────────────── */

  var docEl = document.documentElement;

  function dict(lang) {
    return I18N[lang] || I18N[DEFAULT_LANG];
  }

  function translate(lang, key) {
    var table = dict(lang);
    if (Object.prototype.hasOwnProperty.call(table, key)) return table[key];
    return I18N[DEFAULT_LANG][key];
  }

  function setMeta(selector, value) {
    var el = document.querySelector(selector);
    if (el && value) el.setAttribute("content", value);
  }

  function applyLang(lang) {
    if (SUPPORTED.indexOf(lang) === -1) lang = DEFAULT_LANG;

    var nodes = document.querySelectorAll("[data-i18n]");
    var i, el, val;

    for (i = 0; i < nodes.length; i++) {
      el = nodes[i];
      val = translate(lang, el.getAttribute("data-i18n"));
      if (typeof val === "string") el.textContent = val;
    }

    nodes = document.querySelectorAll("[data-i18n-html]");
    for (i = 0; i < nodes.length; i++) {
      el = nodes[i];
      val = translate(lang, el.getAttribute("data-i18n-html"));
      if (typeof val === "string") el.innerHTML = val;
    }

    nodes = document.querySelectorAll("[data-i18n-label]");
    for (i = 0; i < nodes.length; i++) {
      el = nodes[i];
      val = translate(lang, el.getAttribute("data-i18n-label"));
      if (typeof val === "string") el.setAttribute("aria-label", val);
    }

    document.title = translate(lang, "meta.title");
    setMeta('meta[name="description"]', translate(lang, "meta.desc"));
    setMeta('meta[property="og:title"]', translate(lang, "meta.title"));
    setMeta('meta[property="og:description"]', translate(lang, "meta.desc"));
    setMeta('meta[property="og:locale"]', OG_LOCALE[lang]);
    setMeta('meta[name="twitter:title"]', translate(lang, "meta.title"));
    setMeta('meta[name="twitter:description"]', translate(lang, "meta.desc"));

    docEl.setAttribute("lang", lang);
    docEl.setAttribute("data-lang", lang);

    try { localStorage.setItem(STORAGE_KEY, lang); } catch (e) {}
  }

  function storedLang() {
    var stored = null;
    try { stored = localStorage.getItem(STORAGE_KEY); } catch (e) {}
    return SUPPORTED.indexOf(stored) !== -1 ? stored : DEFAULT_LANG;
  }

  /* ── init ──────────────────────────────────────────────────────────── */

  function init() {
    var lang = storedLang();
    var select = document.getElementById("langSelect");

    if (lang !== DEFAULT_LANG) applyLang(lang);
    if (select) {
      select.value = lang;
      select.addEventListener("change", function () {
        applyLang(select.value);
        closeNav();
      });
    }

    docEl.classList.remove("i18n-pending");

    /* mobile navigation */
    var toggle = document.getElementById("navToggle");
    var menu = document.getElementById("navMenu");

    function closeNav() {
      if (!menu || !toggle) return;
      menu.classList.remove("is-open");
      toggle.setAttribute("aria-expanded", "false");
    }

    if (toggle && menu) {
      toggle.addEventListener("click", function () {
        var open = menu.classList.toggle("is-open");
        toggle.setAttribute("aria-expanded", open ? "true" : "false");
      });

      menu.addEventListener("click", function (event) {
        if (event.target.tagName === "A") closeNav();
      });

      document.addEventListener("keydown", function (event) {
        if (event.key === "Escape") closeNav();
      });
    }
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
